import { Header, Footer, Container } from "@/components";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import ToastContext from "@/components/ToastContext";
import { EdgeStoreProvider } from "../lib/edgestore";
import SessionProvider from "@/components/SesssionProvider";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="relative">
        <SessionProvider>
          <Header />
          <ToastContext />
          <EdgeStoreProvider>{children}</EdgeStoreProvider>
          <Footer />
        </SessionProvider>
      </body>
    </html>
  );
}
